import turtle
turtle.pensize(10)
turtle.up()
turtle.goto(-110,-25)
turtle.down()
turtle.pencolor("red")
turtle.circle(45,360)
turtle.up()
turtle.goto(0,-25)
turtle.down()
turtle.pencolor("blue")
turtle.circle(45,360)
turtle.up()
turtle.goto(110,-25)
turtle.down()
turtle.pencolor("darkgreen")
turtle.circle(45,360)
turtle.up()
turtle.goto(-55,-75)
turtle.down()
turtle.pencolor("yellow")
turtle.circle(45,360)
turtle.up()
turtle.goto(55,-75)
turtle.down()
turtle.pencolor("black")
turtle.circle(45,360)
print("hello zhang")